name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: latest
        cabal-version: latest
        
    - name: Freeze
      run: |
        cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    
    - name: cabal update and build
      run: |
            cabal update
            cabal install
            cabal build
    
    - name: list packages
      run: ghc-pkg list
    
    - name: remove unneccessary libs
      run: | 
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\ghc-8.6.5' -Recurse
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\Cabal-2.4.0.1' -Recurse
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\rts' -Recurse
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\bin' -Recurse
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\html' -Recurse
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\latex' -Recurse
            Remove-Item 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\include' -Recurse
    - name: move GHC libs and configs
      run: Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
    - name: List Folders
      run: |
            cd 'C:\Users\runneradmin\AppData\Roaming'
            ls 
            cd 'C:\Users\runneradmin\AppData\Roaming\cabal'
            ls
    
