name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
  
    - name: move GHC libs
      run: | 
            cd 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib'
            ls
            Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\package.conf.d' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\package.conf.d'
            Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\x86_64-windows-ghc-8.6.5' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\x86_64-windows-ghc-8.6.5'
            Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\llvm-passes' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\llvm-passes'
            Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\llvm-targets' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\llvm-targets'
            Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\platformConstants' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\platformConstants'
            Copy-Item -Path 'C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\settings' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\settings'
    - name: List Folders
      run: ls
    
