name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ['9.0.1']
        cabal: ['3.4.0.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: |
        cabal freeze

    - name: Cache cabal
      uses: actions/cache@v2
      id: cache
      with:
        path: 'C:\sr'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    
    - name: cabal update and build
      #if: steps.cache.outputs.cache-hit != 'true'
      run: |
            cabal v2-update
            cabal v2-install
            cabal v2-build --only-dependencies --enable-tests
    
    - name: try
      run: echo 'import Sound.Tidal.Pattern' | ghci
    
    - name: remove unneccessary libs 
      run: | 
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\ghc-${{ matrix.ghc }}' -Recurse
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\Cabal-${{ matrix.cabal }}' -Recurse
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\rts-1.0' -Recurse
    - name: move GHC libs and configs
      run: |
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\x86_64-windows-ghc-${{ matrix.ghc }}\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\package.conf.d' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\package.conf.d\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\llvm-passes' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\llvm-passes'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\llvm-targets' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\llvm-targets'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\platformConstants' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\platformConstants'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\settings' -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\settings'
    - name: move mingw
      run: Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\mingw'
      
    - name: List Folders
      run: |
            cd 'C:\sr\ghc-${{ matrix.ghc }}'
            ls 
