name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ['9.0.1']
        cabal: ['3.4']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: |
        cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    
    - name: cabal update and build
      run: |
            cabal update
            cabal install
            cabal build
    
    - name: list packages
      run: ghc-pkg list
    
    - name: remove unneccessary libs 
      run: | 
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\ghc-${{ matrix.ghc }}' -Recurse
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\Cabal-${{ matrix.cabal }}' -Recurse
            Remove-Item 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\rts' -Recurse
    - name: move GHC libs and configs
      run: |
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\x86_64-windows-ghc-${{ matrix.ghc }}\' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\package.conf.d' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\llvm-passes' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\llvm-targets' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\platformConstants' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
            Copy-Item -Path 'C:\tools\ghc-${{ matrix.ghc }}\lib\settings' -Recurse -Destination 'D:\a\tidal-deploy\tidal-deploy\binary\libs\'
    - name: List Folders
      run: |
            cd 'C:\Users\runneradmin\AppData\Roaming'
            ls 
            cd 'C:\Users\runneradmin\AppData\Roaming\cabal'
            ls
    
