name: Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        ghc: ['9.0.1']
        cabal: ['3.4.0.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: |
        cabal freeze
    - name: Cache cabal
      uses: actions/cache@v2
      id: cache-cabal
      with:
        path: '~/.cabal'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/src/Main.hs') }}-a
        
    - name: Cache dist
      uses: actions/cache@v2
      id: cache-bin
      with:
        path: '/dist-newstyle/'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/src/Main.hs') }}-b
    
    - name: cabal update and build
      run: cabal v2-build --enable-tests
    
    - name : make directory
      run: |
            mkdir binary
            mkdir binary/haskell-libs/
            mkdir binary/c-libs/
            ls
            
    - name: move GHC libs and configs
      run: |
            mkdir binary/haskell-libs/ghc-packages/
            cd ${{ steps.setup-haskell-cabal.outputs.ghc-path }}
            cd ..
            cd lib
            cp -R ghc-${{ matrix.ghc }}/* /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages
            
    - name: move installed packages
      run: | 
            mkdir binary/haskell-libs/packages/
            cp -R ${{ steps.setup-haskell-cabal.outputs.cabal-store }}/ghc-${{ matrix.ghc }}/* binary/haskell-libs/packages
            ls binary/haskell-libs/packages
   
    - name: change paths in config files (GHC)
      run: |
            mv /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages/package.conf.d /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.conf.d
            cd /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.conf.d/
            sed -i 's/\/opt\/ghc\/${{ matrix.ghc }}\/lib\/ghc-${{ matrix.ghc }}/${pkgroot}\/ghc-packages/g' *
     
    - name: change paths in config files (cabal)
      run: |
            mv /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/packages/package.db /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.db
            cd /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.db/
            sed -i 's/\/Users\/runner\/.cabal\/store\/ghc-${{ matrix.ghc }}/${pkgroot}\/packages/g' *
   
    - name: move ghc settings etc
      run: |
            mv /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages/settings /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/settings
            mv /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages/platformConstants /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/platformConstants
            mv /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages/llvm-targets /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/llvm-targets
            mv /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages/llvm-passes /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/llvm-passes

    - name: ghc-pkg recache
      run: |
            ghc-pkg --package-db=/Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.conf.d recache
            ghc-pkg --package-db=/Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.db recache
            ghc-pkg --package-db=/Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.conf.d --package-db=/Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/package.db check
   
    - name: remove unneccessary libs 
      run: |
            cd /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/ghc-packages
            rm -R ghc-${{ matrix.ghc }}
            rm -R Cabal-${{ matrix.cabal }}
            rm -R rts
            
    - name: fake gcc
      run: |
            mkdir binary/bin
            cp -R fake_gcc.sh binary/bin/fake_gcc.sh
            sed -i 's/cc/bin\/fake_gcc.sh/g' /Users/runner/work/tidal-deploy/tidal-deploy/binary/haskell-libs/settings
   
    - name: move executable
      run: cp -R dist-newstyle/build/x86_64-osx/ghc-9.0.1/my-program-0.1.0.0/x/my-program/build/my-program/my-program binary/my-program
  
    - name: zip files
      run: |
            cd /Users/runner/work/tidal-deploy/tidal-deploy/
            tar cvfj binary.tar binary/*
    - uses: actions/upload-artifact@v2
      with:
        name: my-program
        path: /Users/runner/work/tidal-deploy/tidal-deploy/binary.tar
